# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodPath--Camera' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodPath--Camera
	pod 'Parse'

  target 'FoodPath--CameraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodPath--CameraUITests' do
    # Pods for testing
  end

end
